name: ci

on: [push]

jobs:
  test:
    name: test - PHP ${{matrix.php-version}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.2', '7,3', '7.4', '8.0']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Use PHP ${{matrix.php-version}}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{matrix.php-version}}
          coverage: xdebug

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{steps.composercache.outputs.dir}}
          key: ${{runner.os}}-composer-${{hashFiles('**/composer.json')}}
          restore-keys: ${{runner.os}}-composer-

      - run: composer install --no-progress --prefer-dist
      - run: composer run test

  coverage:
    name: coverage
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          coverage: xdebug

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v2
        with:
          path: ${{steps.composercache.outputs.dir}}
          key: ${{runner.os}}-composer-${{hashFiles('**/composer.json')}}
          restore-keys: ${{runner.os}}-composer-

      - run: composer install --no-progress --prefer-dist
      - run: composer run coverage

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          name: coverage
          flags: unittests
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./build/logs/coverage-clover.xml
          path_to_write_report: ./build/logs/coverage-clover.gz
          fail_ci_if_error: true
          verbose: true